version: "3"
services:
  web:
    image: aomkirby12/opener-api:1.2.0
    deploy:
      replicas: 8
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:4000"
    networks:
      - webnet
networks:
  webnet: